# Generated by Django 5.1.5 on 2025-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
